name: Publish new Release
on:
  workflow_dispatch:
jobs:
  publish:
    name: Sync tags with latest Retype release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update and Release
        shell: bash
        run: .github/workflows/refresh-release.sh --github-token="${{ secrets.GITHUB_TOKEN }}"
